# Generated by Django 3.1.4 on 2021-02-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEEcalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OEE', models.IntegerField(max_length=2)),
                ('A', models.IntegerField(max_length=2)),
                ('P', models.IntegerField(max_length=2)),
                ('Q', models.IntegerField(max_length=2)),
            ],
        ),
    ]
