# Generated by Django 3.1.4 on 2021-02-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_auto_20210208_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeecalculations',
            name='A',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='oeecalculations',
            name='OEE',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='oeecalculations',
            name='P',
            field=models.FloatField(max_length=3),
        ),
        migrations.AlterField(
            model_name='oeecalculations',
            name='Q',
            field=models.FloatField(max_length=3),
        ),
    ]
