# Generated by Django 3.1.4 on 2021-02-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_auto_20210208_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='OEE',
            field=models.FloatField(default=75, max_length=3),
            preserve_default=False,
        ),
    ]
