# Generated by Django 3.1.4 on 2021-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0007_student_oee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='OEE',
            field=models.FloatField(blank=True, max_length=3, null=True),
        ),
    ]
