# Generated by Django 3.1.4 on 2021-02-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0008_auto_20210210_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oeecalculations',
            name='A',
            field=models.FloatField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='oeecalculations',
            name='OEE',
            field=models.FloatField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='oeecalculations',
            name='P',
            field=models.FloatField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='oeecalculations',
            name='Q',
            field=models.FloatField(max_length=3, null=True),
        ),
    ]
