# Generated by Django 3.1.4 on 2021-02-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0009_auto_20210210_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('uemail', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('martialstatus', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'newuserreg',
            },
        ),
    ]
